# version: '3.8'  # Removed to avoid obsolete warning

services:
  mysql:
    image: mysql:8.0
    container_name: webtestflow-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-123456}
      MYSQL_DATABASE: ${DB_NAME:-webtestflow}
      MYSQL_USER: ${DB_USERNAME:-webtestflow}
      MYSQL_PASSWORD: ${DB_PASSWORD:-123456}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./deployments/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webtestflow-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  webtestflow-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: webtestflow-app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - SERVER_MODE=release
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=${DB_USERNAME:-webtestflow}
      - DB_PASSWORD=${DB_PASSWORD:-123456}
      - DB_NAME=${DB_NAME:-webtestflow}
      - JWT_SECRET=${JWT_SECRET:-webtestflow-secret-key-change-in-production}
      - CHROME_HEADLESS=true
      - CHROME_MAX_INSTANCES=10
      - OCR_SERVICE_URL=http://ocr-service:8888
    ports:
      - "8080:8080"
    volumes:
      - app_uploads:/app/uploads
      - app_screenshots:/app/screenshots
      - app_logs:/app/logs
    networks:
      - webtestflow-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ocr-service:
    build:
      context: ./services/ocr
      dockerfile: Dockerfile
    container_name: webtestflow-ocr
    restart: always
    environment:
      - OCR_HOST=0.0.0.0
      - OCR_PORT=8888
    ports:
      - "8888:8888"
    networks:
      - webtestflow-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8888/health')"]
      interval: 30s
      timeout: 3s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: webtestflow-nginx
    restart: always
    depends_on:
      - webtestflow-app
      - ocr-service
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployments/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deployments/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - app_uploads:/var/www/uploads:ro
      - app_screenshots:/var/www/screenshots:ro
    networks:
      - webtestflow-network

volumes:
  mysql_data:
    driver: local
  app_uploads:
    driver: local
  app_screenshots:
    driver: local
  app_logs:
    driver: local

networks:
  webtestflow-network:
    driver: bridge